# Generated by Django 5.1.4 on 2025-01-15 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_account_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='employee_account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.IntegerField()),
                ('account_id', models.IntegerField()),
            ],
        ),
    ]
