# Generated by Django 5.1.4 on 2025-01-15 03:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_account_table_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee_table',
            name='login',
        ),
    ]
