# Generated by Django 5.1.4 on 2025-01-15 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_employee_table_login'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee_table',
            name='name',
        ),
        migrations.RemoveField(
            model_name='employee_table',
            name='token',
        ),
        migrations.AlterField(
            model_name='employee_table',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
        migrations.AlterField(
            model_name='employee_table',
            name='position',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='employee_table',
            name='role',
            field=models.CharField(blank=True, choices=[('administrator', 'Администратор'), ('manager', 'Менеджер'), ('executor', 'Исполнитель')], max_length=50, null=True),
        ),
    ]
